### ISSUE TITLE
rna-transcription: don't transcribe both ways

### ISSUE THREAD

**Issue by kytrinyx** [exercism/plsql#11]
I can't remember the history of this, but we ended up with a weird non-biological thing in the RNA transcription exercise, where some test suites also have tests for transcribing from RNA back to DNA. This makes no sense.

If this track does have tests for the reverse transcription, we should remove them, and also simplify the reference solution to match.

If this track doesn't have any tests for RNA->DNA transcription, then this issue can be closed.

See https://github.com/exercism/x-common/issues/148

**Comment by chezwicker** [comment]
I always thought this made sense from the programming side even if it's nonsense in terms of biology: it makes sure the solution doesn't hard code values but abstracts by e.g. defining source -> target "maps" that can be passed to the algo used.

I would value this more than consistency with reality. Maybe we could rephrase and state that sometimes we find isolated RNA and want to know what DNA strand it resulted from...

**Comment by kytrinyx** [comment]
Yeah, rephrasing it would work. I don't have a strong opinion. I didn't think about the fact that reversing it would avoid hard-coding, that's a good reason to keep the reverse algorithm. Would you mind making that point in the original/top-level thread?

**Comment by chezwicker** [comment]
Sure, will do!

**Comment by kytrinyx** [comment]
When you decide to update the description, then go ahead and copy the `description.md` file from problem-specifications to `exercises/rna-transcription/.meta/description.md` and update it here. Thanks!
