### ISSUE TITLE
Genericize plsql?

### ISSUE THREAD

**Issue by dgdosen** [exercism/plsql#54]
Hi all;

I think exercism is an ideal place to learn about sql procs - but did you all ever think of 'widening' the scope of this track to include PL/pgSQL?  

I'm not sure if there is a lowest common denominator between the two, but I'd be more inclined to using this track if was based on psql.

**Comment by iHiD** [comment]
Sorry this didn't get responded to. I'd love to have a wider spec'd track but we'd need someone willing to spearhead it.
